site_name: Constellation
#site_url: https://constellation.readthedocs.io
nav:
    - Home: index.md
    - GitHub: index.md
    - 'Constellation':
        - Overview : user-guide//index.md
    - 'Graph':
        - Overview : user-guide/graph/index.md
        - 'Visualisation':
            - Overview : user-guide/graph/visualisation/index.md
        - 'Editing':
            - Overview : user-guide/graph/editing/index.md
        - 'I/O':
            - Overview : user-guide/graph/i_o/index.md
        - 'File Operations':
            - Overview : user-guide/graph/file_operations/index.md
    - 'Arrangements':
        - Overview : user-guide/arrangements/index.md
    - 'Preferences':
        - Overview : user-guide/preferences/index.md
    - 'Views':
        - Overview : user-guide/views/index.md
        - 'Data Access View':
            - Overview : user-guide/views/data_access_view/index.md
            - 'Import':
                - Overview : user-guide/views/data_access_view/import/index.md
            - 'Clean':
                - Overview : user-guide/views/data_access_view/clean/index.md
            - 'Developer':
                - Overview : user-guide/views/data_access_view/developer/index.md
            - 'Global Parameters':
                - Overview : user-guide/views/data_access_view/global_parameters/index.md
            - 'Utility':
                - Overview : user-guide/views/data_access_view/utility/index.md
        - 'Map View':
            - Overview : user-guide/views/map_view/index.md
            - 'Layers':
                - Overview : user-guide/views/map_view/layers/index.md
            - 'Overlays':
                - Overview : user-guide/views/map_view/overlays/index.md
        - 'Analytic View':
            - Overview : help/html/analytic-view.md
            - 'Questions':
                - Overview : user-guide/views/analytic_view/questions/index.md
            - 'Analytics':
                - Overview : user-guide/views/analytic_view/analytics/index.md
                - 'Centrality':
                    - Overview : user-guide/views/analytic_view/analytics/centrality/index.md
                - 'Global':
                    - Overview : user-guide/views/analytic_view/analytics/global/index.md
                - 'Metrics':
                    - Overview : user-guide/views/analytic_view/analytics/metrics/index.md
                - 'Similarity':
                    - Overview : user-guide/views/analytic_view/analytics/similarity/index.md
    - 'Selection':
        - Overview : user-guide/selection/index.md
    - 'Tools':
        - Overview : user-guide/tools/index.md
        - 'Cluster':
            - Overview : user-guide/tools/cluster/index.md
    - 'Import/Export':
        - Overview : user-guide/import_export/index.md
    - 'Jupyter':
        - Overview : user-guide/jupyter/index.md
    - 'Overview':
        - Overview : user-guide/overview/index.md


theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - java
        - python
